[package]
name = "dungeon-generator"
version = "0.1.0"
edition = "2021"
authors = ["vxdcxw <defresne.thierry@gmail.com>"]

[lib]
crate-type = ["lib","staticlib"]

[dependencies]
libc = "0.2"
clap = { version = "3.2.22", features = ["derive"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
